#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_7
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_6
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_38 // 主麦 + 副麦
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_9
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_10
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_11

#if defined(CONFIG_AUDIO_PROCESSING_ALGORITHM_0)
#define AUDIO_PROCESSING_ALGORITHM AudioProcessingAlgorithm::ALGORITHM_SIMPLE_AVERAGE
#elif defined(CONFIG_AUDIO_PROCESSING_ALGORITHM_1)
#define AUDIO_PROCESSING_ALGORITHM AudioProcessingAlgorithm::ALGORITHM_BEAMFORMING_BASIC
#elif defined(CONFIG_AUDIO_PROCESSING_ALGORITHM_2)
#define AUDIO_PROCESSING_ALGORITHM AudioProcessingAlgorithm::ALGORITHM_NOISE_SUPPRESSION
#else
#define AUDIO_PROCESSING_ALGORITHM AudioProcessingAlgorithm::ALGORITHM_NOISE_SUPPRESSION
#endif

#define BUILTIN_LED_GPIO  GPIO_NUM_4
#define BOOT_BUTTON_GPIO  GPIO_NUM_0

#define DISPLAY_SDA_PIN GPIO_NUM_41
#define DISPLAY_SCL_PIN GPIO_NUM_42
#define DISPLAY_WIDTH   128

#if CONFIG_OLED_SSD1306_128X32
#define DISPLAY_HEIGHT  32
#elif CONFIG_OLED_SSD1306_128X64
#define DISPLAY_HEIGHT  64
#elif CONFIG_OLED_SH1106_128X64
#define DISPLAY_HEIGHT  64
#define SH1106
#else
#error "未选择 OLED 屏幕类型"
#endif

#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true

#endif // _BOARD_CONFIG_H_
